[build]
  publish = "."

# Подключаем Edge Function для всех входящих маршрутов
[[edge_functions]]
  path = "/*"
  function = "b24"

[[headers]]
  for = "/*"
    [headers.values]
      Content-Security-Policy = "frame-ancestors *;"
      X-Frame-Options = "ALLOWALL"
      Access-Control-Allow-Origin = "*"
      Access-Control-Allow-Methods = "GET, POST, OPTIONS"
      Access-Control-Allow-Headers = "Content-Type, Authorization"
